server {
    listen 80;

    # -------------------------
    # STATIC FILES
    # -------------------------
    location /static/ {
        alias /static/;
    }

    # -------------------------
    # MEDIA FILES (uploads)
    # -------------------------
    location /media/ {
        alias /media/;
    }

    # -------------------------
    # DJANGO APP
    # -------------------------
    location / {
        proxy_pass http://gallery_app:8010;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
